### ISSUE TITLE
[Feat]: 컨트롤러 레이어 작성

### ISSUE THREAD

**Issue by Istiopaxx** [kraftenty/place-finder#8]
## TODO

- [x] 컨트롤러 클래스 작성
- [x] @RestController, @RequestMapping, @PostMapping, @GetMapping @RequestBody, @RequestParam 등등 어노테이션 활용
- [x] 서비스 클래스 메소드 호출하면됨
- [x] DTO 만드는 것도 필수
- 테스트 작성 불필요
